apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: weatherforecast-csharp
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: sample-app
    apps.tanzu.vmware.com/scanning: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1682466086870371062"
    kapp.k14s.io/association: v1.0caae3a4904957f80dc0f74b0090ae2d
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-csharp
    app.kubernetes.io/component: run
    carto.run/workload-name: weatherforecast-csharp
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-steeltoe
          appliveview-sample/app-live-view-appflavours-steeltoe
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;workload-corby/carto.run/Workload/weatherforecast-csharp;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"sample-app","apps.tanzu.vmware.com/scanning":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1682466086870371062","kapp.k14s.io/association":"v1.0caae3a4904957f80dc0f74b0090ae2d","tanzu.app.live.view":"true","tanzu.app.live.view.application.flavours":"steeltoe","tanzu.app.live.view.application.name":"weatherforecast-csharp"},"name":"weatherforecast-csharp","namespace":"workload-corby"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"api_descriptor","value":{"description":"A set of API endpoints to manage the resources within the petclinic app.","location":{"path":"/swagger/v1/swagger.json"},"owner":"team-petclinic","system":"pet-clinics","type":"openapi"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/vmware-tanzu/application-accelerator-samples"},"subPath":"csharp-weatherforecast"}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: sample-app
        apps.tanzu.vmware.com/scanning: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: weatherforecast-csharp
        kapp.k14s.io/app: "1682466086870371062"
        kapp.k14s.io/association: v1.0caae3a4904957f80dc0f74b0090ae2d
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: steeltoe
        tanzu.app.live.view.application.name: weatherforecast-csharp
    spec:
      containers:
      - image: gcr.io/fe-cpage/tap/supply-chain/weatherforecast-csharp-workload-corby@sha256:bf2e2afe754aee0684d5a68f02fcf11fe49c7ff905e241ab7fa309583a987885
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

