---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: app
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 packageRef:
   refName: spring-sensors.iterate-corby.tap # name of the Package
   versionSelection:
     constraints: 20230828183150.0.0 # version of the Package
 values:
 - secretRef:
     name: app-values # Secret created in previous step
