apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: where-for-dinner-ui
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: where-for-dinner-ui
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    kapp.k14s.io/app: "1682466086870371062"
    kapp.k14s.io/association: v1.0771ea60a569cc23440cb8d36ac1e529
    networking.knative.dev/visibility: cluster-local
    app.kubernetes.io/component: run
    carto.run/workload-name: where-for-dinner-ui
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kapp.k14s.io/identity: v1;workload-corby/carto.run/Workload/where-for-dinner-ui;carto.run/v1alpha1
        kapp.k14s.io/original: '{"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"labels":{"app.kubernetes.io/part-of":"where-for-dinner-ui","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web","kapp.k14s.io/app":"1682466086870371062","kapp.k14s.io/association":"v1.0771ea60a569cc23440cb8d36ac1e529","networking.knative.dev/visibility":"cluster-local"},"name":"where-for-dinner-ui","namespace":"workload-corby"},"spec":{"build":{"env":[{"name":"BP_NODE_RUN_SCRIPTS","value":"build"},{"name":"BP_WEB_SERVER_ROOT","value":"dist"}]},"env":[{"name":"REACT_APP_PROFILE","value":"nonsecure"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}}],"resources":{"limits":{"cpu":"1500m","memory":"750M"},"requests":{"cpu":"100m","memory":"500M"}},"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/cpage-pivotal/where-for-dinner"},"subPath":"where-for-dinner-ui"}}}'
        kapp.k14s.io/original-diff-md5: c6e94dc94aed3401b5d0f26ed6c0bff3
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: where-for-dinner-ui
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: where-for-dinner-ui
        kapp.k14s.io/app: "1682466086870371062"
        kapp.k14s.io/association: v1.0771ea60a569cc23440cb8d36ac1e529
        networking.knative.dev/visibility: cluster-local
    spec:
      containers:
      - env:
        - name: REACT_APP_PROFILE
          value: nonsecure
        image: gcr.io/fe-cpage/tap/supply-chain/where-for-dinner-ui-workload-corby@sha256:f60e480a95af9333fafa584e6dd5f69b84122bd4269957c0b67db8e1955e4d19
        name: workload
        resources:
          limits:
            cpu: 1500m
            memory: 750M
          requests:
            cpu: 100m
            memory: 500M
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

